### ISSUE TITLE
[question] more info about this module?

### ISSUE THREAD

**Issue by 1LineAtaTime** [rarnu/wechat_no_revoke#3]
Hi! I have downloaded your module for Wechat, but I am not sure if I understand what this module does. I thought it was so the messages from Wechat in the status bar don't dissapear after reboot and so on. Am I right? If not, would you mind explaining it please?

**Comment by tavimori** [comment]
Not exactly. In fact, "revoke" is a WeChat's function, which can revoke a message you've already sent within the first 2 mins (remotely delete the msg on the receiver's devices). This module may prevent it - so that others cannot cancel their msg.

BTW, if you want to try "revoke", just send any msg and long press on it.

**Comment by 1LineAtaTime** [comment]
Gotcha, I did not know of that feature!
Thanks for your time and effort :)
